apiVersion: v1
kind: Pod
metadata:
  name: myapp-php
  labels:
    app: myapp-php
spec:
  containers:
  - name: myapp-php
    image: erimendes/myapp-php:1.0
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-php-service
spec:
  type: NodePort
  selector:
    app: myapp-php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

---

apiVersion: v1
kind: Deployment
metadata:
  name: myapp-php-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-php
  template:
    metadata:
      labels:
        app: myapp-php
    spec:
      containers:
        - name: myapp-php
          image: erimendes/myapp-php:1.0
          ports:
            - containerPort: 80 
